remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

title: ahoque.org
description: Personal Blog
domain: ahoque.org
url: https://ahoque.org
baseurl: /ahoqueali.github.io
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
