remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: ahoque.org
description: Personal Blog Site
domain: ahoque.org
url: https://ahoque.org
baseurl: /ahoqueali.github.io/ 
