theme: jekyll-theme-minimal
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: ahoque.org
analytics:
  provider: "google-universal"
  google:
 	tracking_id: "UA-127414532-1"
